name: app
type: "php:8.4"

build:
    flavor: composer

runtime:
    extensions:
        - mongodb
    variables_order: "EGPCS"

web:
    locations:
        '/':
            root: 'public'
            passthru: '/index.php'
            allow: true
            expires: -1
            scripts: true
            index:
                - index.php

mounts:
    '/var': 'shared:files/var'
    '/var/cache': 'shared:files/cache'
    '/var/log': 'shared:files/log'

disk: 512

hooks:
    build: |
        set -e
        composer install --no-dev --prefer-dist --optimize-autoloader

    deploy: |
        php bin/console cache:clear --env=prod --no-warmup
        php bin/console cache:warmup --env=prod

variables:
    env:
        APP_ENV: "prod"
        BATCH_SIZE: 25
        MAX_RETRIES: 3
        MONGODB_URL: "mongodb://guest:guest@demo-shard-00-00.k5dqp.mongodb.net:27017,demo-shard-00-01.k5dqp.mongodb.net:27017,demo-shard-00-02.k5dqp.mongodb.net:27017/?replicaSet=atlas-4cih2q-shard-0&ssl=true&authSource=admin&retryWrites=true&w=majority&appName=demo"
        MONGODB_DB: "ChatBotApp"
        OPENAI_API_KEY: "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"
        OPENAI_API_URL: "https://api.openai.com/v1/chat/completions"
        VOYAGE_API_KEY: "pa-h-nqjmbdNk-pubD6Qqx-bvE4VSsqVHiEHQvslgdAlga"
        VOYAGE_ENDPOINT: "https://api.voyageai.com/v1/embeddings"
    
