name: app
type: "php:8.4"

build:
    flavor: composer

runtime:
    extensions:
        - mongodb
    variables_order: "EGPCS"

web:
    locations:
        '/':
            root: 'public'
            passthru: '/index.php'
            allow: true
            expires: -1
            scripts: true
            index:
                - index.php

mounts:
    '/var': 'shared:files/var'
    '/var/cache': 'shared:files/cache'
    '/var/log': 'shared:files/log'

disk: 512

hooks:
    build: |
        set -e
        composer install --no-dev --prefer-dist --optimize-autoloader

    deploy: |
        php bin/console cache:clear --env=prod --no-warmup
        php bin/console cache:warmup --env=prod

variables:
    env:
        APP_ENV: "prod"
        BATCH_SIZE: 25
        MAX_RETRIES: 3
        MONGODB_URL: "<Atlas URI>"
        MONGODB_DB: "<Database Name>"
        OPENAI_API_KEY: "<OPEN AI key>"
        OPENAI_API_URL: "https://api.openai.com/v1/chat/completions"
        VOYAGE_API_KEY: "Voyage AI Key"
        VOYAGE_ENDPOINT: "https://api.voyageai.com/v1/embeddings"
    
