<?php

namespace ContainerP9sLRCu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateChunks_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\CreateChunks.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\CreateChunks.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:create-chunks', [], 'This command will generate chunks from the rst files and store into MongoDB', false, #[\Closure(name: 'App\\Command\\CreateChunks')] fn (): \App\Command\CreateChunks => ($container->privates['App\\Command\\CreateChunks'] ?? $container->load('getCreateChunksService')));
    }
}
