<?php

namespace ContainerLEQfauc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmbeddedChunks_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\EmbeddedChunks.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\EmbeddedChunks.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:embed-chunks', [], 'This command will create embedding for the stored chunks using Voyage AI API key and store into MongoDB database', false, #[\Closure(name: 'App\\Command\\EmbeddedChunks')] fn (): \App\Command\EmbeddedChunks => ($container->privates['App\\Command\\EmbeddedChunks'] ?? $container->load('getEmbeddedChunksService')));
    }
}
