<?php

namespace ContainerZfkE9hx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateChunksService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\CreateChunks' shared autowired service.
     *
     * @return \App\Command\CreateChunks
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/CreateChunks.php';

        $container->privates['App\\Command\\CreateChunks'] = $instance = new \App\Command\CreateChunks(($container->services['doctrine_mongodb.odm.default_document_manager'] ?? $container->load('getDoctrineMongodb_Odm_DefaultDocumentManagerService')));

        $instance->setName('app:createChunks');
        $instance->setDescription('This command will generate chunks from the rst files and store into MongoDB');

        return $instance;
    }
}
