<?php

namespace Container2KXDDT6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChatControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ChatController' shared autowired service.
     *
     * @return \App\Controller\ChatController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/ChatController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/ResponseService.php';

        $container->services['App\\Controller\\ChatController'] = $instance = new \App\Controller\ChatController(new \App\Service\ResponseService(($container->services['doctrine_mongodb.odm.default_document_manager'] ?? $container->load('getDoctrineMongodb_Odm_DefaultDocumentManagerService')), $container->getEnv('OPENAI_API_KEY'), $container->getEnv('OPENAI_API_URL'), $container->getEnv('VOYAGE_API_KEY'), $container->getEnv('VOYAGE_ENDPOINT'), ($container->privates['http_client.uri_template'] ?? $container->load('getHttpClient_UriTemplateService'))));

        $instance->setContainer((new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'router' => ['services', 'router', 'getRouterService', false],
            'request_stack' => ['services', 'request_stack', 'getRequestStackService', false],
            'http_kernel' => ['services', 'http_kernel', 'getHttpKernelService', false],
            'twig' => ['privates', 'twig', 'getTwigService', true],
            'parameter_bag' => ['privates', 'parameter_bag', 'getParameterBagService', false],
        ], [
            'router' => '?',
            'request_stack' => '?',
            'http_kernel' => '?',
            'twig' => '?',
            'parameter_bag' => '?',
        ]))->withContext('App\\Controller\\ChatController', $container));

        return $instance;
    }
}
