<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7FT9Rxs\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7FT9Rxs/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container7FT9Rxs.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container7FT9Rxs\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container7FT9Rxs\App_KernelDevDebugContainer([
    'container.build_hash' => '7FT9Rxs',
    'container.build_id' => '8bfac748',
    'container.build_time' => 1748448757,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container7FT9Rxs');
